import type { AbilityTemplateData, Role } from './types'

// ─── Rarity Base Stat Totals ────────────────────────────────────────

export const RARITY_BASE_TOTALS: Record<string, number> = {
  common: 100,
  uncommon: 130,
  rare: 170,
  epic: 220,
  legendary: 300,
}

// ─── Role Stat Distributions (% of base total) ─────────────────────

export const ROLE_DISTRIBUTIONS: Record<
  Role,
  { hp: number; atk: number; def: number; spd: number; abl: number }
> = {
  striker: { hp: 0.2, atk: 0.3, def: 0.1, spd: 0.25, abl: 0.15 },
  tank: { hp: 0.3, atk: 0.15, def: 0.25, spd: 0.1, abl: 0.2 },
  scout: { hp: 0.15, atk: 0.25, def: 0.1, spd: 0.3, abl: 0.2 },
  support: { hp: 0.25, atk: 0.1, def: 0.2, spd: 0.15, abl: 0.3 },
  bruiser: { hp: 0.25, atk: 0.25, def: 0.2, spd: 0.15, abl: 0.15 },
  specialist: { hp: 0.15, atk: 0.2, def: 0.1, spd: 0.25, abl: 0.3 },
}

// ─── Type-to-Role Mapping ───────────────────────────────────────────

export const TYPE_TO_ROLE: Record<string, Role> = {
  // Core dinosaur types
  'large theropod': 'striker',
  'small theropod': 'scout',
  sauropod: 'tank',
  'armoured dinosaur': 'tank',
  ceratopsian: 'bruiser',
  euornithopod: 'support',

  // Marine/aquatic
  Pterosauria: 'scout',
  Ichthyosauria: 'specialist',
  Plesiosauria: 'specialist',
  Eurypterida: 'striker',

  // Archosaurs
  Saurischia: 'bruiser',
  Ornithischia: 'bruiser',
  Crocodylia: 'bruiser',

  // Mammals
  Proboscidea: 'tank',
  Mammalia: 'bruiser',
  Perissodactyla: 'bruiser',
  Artiodactyla: 'support',
  Condylarthra: 'bruiser',
  Cimolesta: 'scout',
  Multituberculata: 'scout',
  Sirenia: 'support',
  Primates: 'support',
  Lagomorpha: 'scout',
  Rodentia: 'scout',

  // Reptiles/amphibians
  Squamata: 'scout',
  Reptilia: 'bruiser',
  Temnospondyli: 'specialist',
  Urodela: 'specialist',
  Anura: 'scout',

  // Placoderms/fish
  Phlyctaeniiformes: 'specialist',
  Actinolepidiformes: 'specialist',
  Bothriolepidiformes: 'specialist',
  Asterolepidiformes: 'tank',

  // Trilobites
  Asaphida: 'tank',
  Phacopida: 'bruiser',
  Odontopleurida: 'specialist',
  Corynexochida: 'bruiser',
  Trinucleida: 'support',
  Redlichiida: 'bruiser',

  // Birds
  Hesperornithiformes: 'specialist',
  Ichthyornithes: 'scout',
  Anseriformes: 'support',
  Columbiformes: 'scout',
  Charadriiformes: 'scout',
  Galliformes: 'bruiser',
  Sphenisciformes: 'specialist',

  // Data error: Lesothosaurus has "1.0m" as type (size leaked)
  '1.0m': 'support',
}

// ─── Diet Fallback ──────────────────────────────────────────────────

export const DIET_TO_ROLE: Record<string, Role> = {
  Carnivorous: 'striker',
  Herbivorous: 'tank',
  Piscivorous: 'specialist',
  Omnivorous: 'bruiser',
  'Herbivorous/omnivorous': 'tank',
  Unknown: 'bruiser',
}

export const DEFAULT_ROLE: Role = 'bruiser'

// ─── Active Ability Templates (35) ──────────────────────────────────

export const ACTIVE_ABILITY_TEMPLATES: AbilityTemplateData[] = [
  // ── Damage (single target) ──
  {
    id: 'bite',
    name: 'Bite',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.2,
    cooldown: 0,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'A powerful bite attack.',
  },
  {
    id: 'claw_strike',
    name: 'Claw Strike',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.0,
    cooldown: 0,
    duration: null,
    statAffected: 'spd',
    effectValue: 10,
    description: 'A quick slash that boosts speed this turn.',
  },
  {
    id: 'horn_charge',
    name: 'Horn Charge',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.5,
    cooldown: 2,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'A devastating charging attack with horns.',
  },
  {
    id: 'crushing_jaw',
    name: 'Crushing Jaw',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.8,
    cooldown: 3,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'The strongest single-target bite, crushing bones.',
  },
  {
    id: 'venom_strike',
    name: 'Venom Strike',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 0.8,
    cooldown: 2,
    duration: 3,
    statAffected: 'poison',
    effectValue: 5,
    description: 'A venomous attack that poisons the target for 5% max HP/turn.',
  },
  {
    id: 'feeding_frenzy',
    name: 'Feeding Frenzy',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.3,
    cooldown: 3,
    duration: null,
    statAffected: 'lifesteal',
    effectValue: 30,
    description: 'A frenzied attack that heals 30% of damage dealt.',
  },
  {
    id: 'dive_attack',
    name: 'Dive Attack',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.4,
    cooldown: 4,
    duration: null,
    statAffected: 'ignore_def',
    effectValue: null,
    description: 'A diving strike that ignores enemy defense.',
  },
  {
    id: 'ambush',
    name: 'Ambush',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.6,
    cooldown: 3,
    duration: null,
    statAffected: 'back_row_bonus',
    effectValue: 0.3,
    description: 'A surprise attack. Bonus damage when striking from the back row.',
  },
  {
    id: 'body_slam',
    name: 'Body Slam',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.3,
    cooldown: 2,
    duration: null,
    statAffected: 'stun_chance',
    effectValue: 30,
    description: 'A heavy slam with a 30% chance to stun.',
  },
  {
    id: 'leech_bite',
    name: 'Leech Bite',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.0,
    cooldown: 2,
    duration: null,
    statAffected: 'lifesteal',
    effectValue: 20,
    description: 'A draining bite that heals 20% of damage dealt.',
  },
  {
    id: 'constrict',
    name: 'Constrict',
    type: 'active',
    category: 'damage',
    target: 'single_enemy',
    multiplier: 1.1,
    cooldown: 2,
    duration: 2,
    statAffected: 'spd',
    effectValue: -20,
    description: 'Wraps around the target, dealing damage and slowing them.',
  },

  // ── Damage (AoE) ──
  {
    id: 'tail_sweep',
    name: 'Tail Sweep',
    type: 'active',
    category: 'aoe_damage',
    target: 'all_enemies',
    multiplier: 0.7,
    cooldown: 2,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'A sweeping tail strike hitting all enemies.',
  },
  {
    id: 'stomp',
    name: 'Stomp',
    type: 'active',
    category: 'aoe_damage',
    target: 'all_enemies',
    multiplier: 0.8,
    cooldown: 3,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'A thunderous stomp shaking the ground beneath all enemies.',
  },
  {
    id: 'screech',
    name: 'Screech',
    type: 'active',
    category: 'aoe_damage',
    target: 'all_enemies',
    multiplier: 0.6,
    cooldown: 2,
    duration: null,
    statAffected: 'abl_scaling',
    effectValue: null,
    description: 'A piercing screech that damages all enemies. Scales with Ability Power.',
  },
  {
    id: 'tidal_wave',
    name: 'Tidal Wave',
    type: 'active',
    category: 'aoe_damage',
    target: 'all_enemies',
    multiplier: 0.7,
    cooldown: 3,
    duration: null,
    statAffected: 'abl_scaling',
    effectValue: null,
    description: 'A crashing wave of force that damages all enemies. Scales with Ability Power.',
  },
  {
    id: 'tremor',
    name: 'Tremor',
    type: 'active',
    category: 'aoe_damage',
    target: 'all_enemies',
    multiplier: 0.5,
    cooldown: 2,
    duration: null,
    statAffected: null,
    effectValue: null,
    description: 'Shakes the earth, dealing light damage to all enemies.',
  },

  // ── Buff ──
  {
    id: 'rally_cry',
    name: 'Rally Cry',
    type: 'active',
    category: 'buff',
    target: 'all_allies',
    multiplier: null,
    cooldown: 4,
    duration: 3,
    statAffected: 'atk',
    effectValue: 20,
    description: 'A rallying roar that boosts all allies\' attack by 20%.',
  },
  {
    id: 'herd_formation',
    name: 'Herd Formation',
    type: 'active',
    category: 'buff',
    target: 'all_allies',
    multiplier: null,
    cooldown: 4,
    duration: 3,
    statAffected: 'def',
    effectValue: 20,
    description: 'Tightens formation, boosting all allies\' defense by 20%.',
  },
  {
    id: 'adrenaline_rush',
    name: 'Adrenaline Rush',
    type: 'active',
    category: 'buff',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: 2,
    statAffected: 'spd',
    effectValue: 30,
    description: 'A surge of adrenaline boosts speed by 30%.',
  },
  {
    id: 'apex_roar',
    name: 'Apex Roar',
    type: 'active',
    category: 'buff',
    target: 'all_allies',
    multiplier: null,
    cooldown: 5,
    duration: 2,
    statAffected: 'atk,def',
    effectValue: 15,
    description: 'A fearsome roar that boosts all allies\' attack and defense by 15%.',
  },
  {
    id: 'primal_surge',
    name: 'Primal Surge',
    type: 'active',
    category: 'buff',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: 2,
    statAffected: 'atk,spd',
    effectValue: 25,
    description: 'Primal instincts surge, boosting own attack by 25% and speed by 15%.',
  },
  {
    id: 'fortify',
    name: 'Fortify',
    type: 'active',
    category: 'buff',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: 3,
    statAffected: 'def',
    effectValue: 30,
    description: 'Hardens defenses, boosting own defense by 30%.',
  },

  // ── Debuff ──
  {
    id: 'intimidate',
    name: 'Intimidate',
    type: 'active',
    category: 'debuff',
    target: 'single_enemy',
    multiplier: null,
    cooldown: 3,
    duration: 3,
    statAffected: 'atk',
    effectValue: -20,
    description: 'An intimidating display that reduces an enemy\'s attack by 20%.',
  },
  {
    id: 'mudslide',
    name: 'Mudslide',
    type: 'active',
    category: 'debuff',
    target: 'all_enemies',
    multiplier: null,
    cooldown: 4,
    duration: 2,
    statAffected: 'spd',
    effectValue: -20,
    description: 'Kicks up mud, slowing all enemies by 20%.',
  },
  {
    id: 'armor_break',
    name: 'Armor Break',
    type: 'active',
    category: 'debuff',
    target: 'single_enemy',
    multiplier: null,
    cooldown: 3,
    duration: 3,
    statAffected: 'def',
    effectValue: -30,
    description: 'Shatters an enemy\'s armor, reducing defense by 30%.',
  },
  {
    id: 'spore_cloud',
    name: 'Spore Cloud',
    type: 'active',
    category: 'debuff',
    target: 'all_enemies',
    multiplier: null,
    cooldown: 4,
    duration: 2,
    statAffected: 'atk',
    effectValue: -15,
    description: 'Releases a cloud of spores that weakens all enemies\' attack by 15%.',
  },

  // ── Heal ──
  {
    id: 'graze',
    name: 'Graze',
    type: 'active',
    category: 'heal',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: null,
    statAffected: 'hp',
    effectValue: 25,
    description: 'Grazes on nearby flora, healing 25% of max HP.',
  },
  {
    id: 'symbiosis',
    name: 'Symbiosis',
    type: 'active',
    category: 'heal',
    target: 'all_allies',
    multiplier: null,
    cooldown: 4,
    duration: null,
    statAffected: 'hp',
    effectValue: 15,
    description: 'A symbiotic bond heals all allies for 15% of max HP.',
  },
  {
    id: 'regenerate',
    name: 'Regenerate',
    type: 'active',
    category: 'heal',
    target: 'self',
    multiplier: null,
    cooldown: 4,
    duration: 3,
    statAffected: 'hot',
    effectValue: 8,
    description: 'Accelerates natural healing, restoring 8% max HP per turn.',
  },
  {
    id: 'mend',
    name: 'Mend',
    type: 'active',
    category: 'heal',
    target: 'all_allies',
    multiplier: null,
    cooldown: 2,
    duration: null,
    statAffected: 'hp',
    effectValue: 20,
    description: 'Mends the wounds of the lowest-HP ally, healing 20% max HP.',
  },

  // ── Utility ──
  {
    id: 'shell_guard',
    name: 'Shell Guard',
    type: 'active',
    category: 'shield',
    target: 'self',
    multiplier: null,
    cooldown: 4,
    duration: 2,
    statAffected: 'shield',
    effectValue: 30,
    description: 'Retreats into a shell, absorbing up to 30% max HP in damage.',
  },
  {
    id: 'headbutt',
    name: 'Headbutt',
    type: 'active',
    category: 'stun',
    target: 'single_enemy',
    multiplier: 0.8,
    cooldown: 4,
    duration: 1,
    statAffected: 'stun',
    effectValue: null,
    description: 'A forceful headbutt that stuns the target for 1 turn.',
  },
  {
    id: 'counter_stance',
    name: 'Counter Stance',
    type: 'active',
    category: 'buff',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: 1,
    statAffected: 'reflect',
    effectValue: 40,
    description: 'Adopts a defensive stance, reflecting 40% of damage taken this turn.',
  },
  {
    id: 'taunt',
    name: 'Taunt',
    type: 'active',
    category: 'taunt',
    target: 'self',
    multiplier: null,
    cooldown: 3,
    duration: 2,
    statAffected: 'taunt',
    effectValue: null,
    description: 'Draws all single-target attacks to self for 2 turns.',
  },

  // ── DoT ──
  {
    id: 'bleed',
    name: 'Bleed',
    type: 'active',
    category: 'dot',
    target: 'single_enemy',
    multiplier: 0.9,
    cooldown: 2,
    duration: 3,
    statAffected: 'bleed',
    effectValue: 4,
    description: 'A slashing wound that bleeds for 4% max HP per turn.',
  },
]

// ─── Passive Ability Templates (15) ─────────────────────────────────

export const PASSIVE_ABILITY_TEMPLATES: AbilityTemplateData[] = [
  {
    id: 'thick_hide',
    name: 'Thick Hide',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'damage_reduction',
    effectValue: 15,
    description: 'Reduces all incoming damage by 15%.',
  },
  {
    id: 'predator_instinct',
    name: 'Predator Instinct',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'atk',
    effectValue: 20,
    description: '+20% ATK against targets below 50% HP.',
  },
  {
    id: 'herd_mentality',
    name: 'Herd Mentality',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'all_stats',
    effectValue: 10,
    description: '+10% all stats per ally of the same creature type.',
  },
  {
    id: 'aquatic_adaptation',
    name: 'Aquatic Adaptation',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'spd,def',
    effectValue: 20,
    description: '+20% SPD, -10% DEF.',
  },
  {
    id: 'venomous',
    name: 'Venomous',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: 2,
    statAffected: 'poison',
    effectValue: 3,
    description: 'Basic attacks apply poison dealing 3% HP/turn for 2 turns.',
  },
  {
    id: 'evasive',
    name: 'Evasive',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'dodge',
    effectValue: 15,
    description: '15% chance to dodge attacks.',
  },
  {
    id: 'apex_predator',
    name: 'Apex Predator',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'stun_immune,atk',
    effectValue: 10,
    description: 'Immune to stun. +10% ATK.',
  },
  {
    id: 'ancient_resilience',
    name: 'Ancient Resilience',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'all_stats',
    effectValue: 5,
    description: '+5% all stats per KO\'d ally. Last-stand scaling.',
  },
  {
    id: 'territorial',
    name: 'Territorial',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'atk,def',
    effectValue: 15,
    description: '+15% ATK and DEF when in the front row.',
  },
  {
    id: 'pack_hunter',
    name: 'Pack Hunter',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'atk',
    effectValue: 10,
    description: '+10% ATK per ally still alive.',
  },
  {
    id: 'regenerative',
    name: 'Regenerative',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'hot',
    effectValue: 3,
    description: 'Heals 3% max HP at the end of each turn.',
  },
  {
    id: 'camouflage',
    name: 'Camouflage',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'untargetable',
    effectValue: 25,
    description: '25% chance to not be targeted by single-target abilities.',
  },
  {
    id: 'armored_plates',
    name: 'Armored Plates',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'crit_damage_reduction',
    effectValue: 50,
    description: 'Reduces critical hit damage taken by 50%.',
  },
  {
    id: 'thermal_regulation',
    name: 'Thermal Regulation',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: 2,
    statAffected: 'debuff_immune',
    effectValue: null,
    description: 'Immune to debuffs for the first 2 turns.',
  },
  {
    id: 'scavenger',
    name: 'Scavenger',
    type: 'passive',
    category: 'passive',
    target: null,
    multiplier: null,
    cooldown: null,
    duration: null,
    statAffected: 'hp',
    effectValue: 15,
    description: 'Heals 15% max HP when an enemy is KO\'d.',
  },
]

export const ALL_ABILITY_TEMPLATES: AbilityTemplateData[] = [
  ...ACTIVE_ABILITY_TEMPLATES,
  ...PASSIVE_ABILITY_TEMPLATES,
]
